#!/usr/bin/env bash
# =============================================================================
# apply-hud-opacity.sh
#
# Applies the HUD opacity slider patch to an Arx Libertatis 1.2.1 source tree.
#
# Generated by Claude Sonnet 4.6 (https://www.anthropic.com/claude)
# running as Claude Code (https://claude.ai/code).
#
# Usage:
#   bash apply-hud-opacity.sh /path/to/ArxLibertatis-1.2.1
#
# What this script does:
#   1. Adds `float hudOpacity` to the Config interface struct (Config.h)
#   2. Adds default value, config key, writer, and clamped reader (Config.cpp)
#   3. Adds a "HUD Opacity" slider to the Interface options page (MainMenu.cpp)
#   4. Adds hudAlpha() helper and OpModulate bracket to the HUD render path (Hud.cpp)
#   5. Applies opacity to the HudIconBase draw function (HudCommon.cpp)
#
# The patch is equivalent to arx-hud-opacity.patch but self-documenting.
# Requires: python3 (for reliable multi-line string replacement)
#
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Argument handling
# ---------------------------------------------------------------------------

if [ $# -ne 1 ]; then
    echo "Usage: $0 /path/to/ArxLibertatis-1.2.1"
    exit 1
fi

ROOT="$1"
SRC="$ROOT/src"

if [ ! -f "$SRC/core/Config.h" ]; then
    echo "ERROR: $SRC/core/Config.h not found — is '$ROOT' the correct source root?"
    exit 1
fi

echo "=== Arx Libertatis HUD opacity patch ==="
echo "Source root: $ROOT"
echo ""

# ---------------------------------------------------------------------------
# Helper: apply a Python string replacement to a file.
# Exits non-zero if the old string is not found (safety check).
# ---------------------------------------------------------------------------

replace() {
    local FILE="$1"
    # old string is read from fd 3, new string from fd 4 via process substitution
    python3 - "$FILE" <<'PYEOF'
import sys

filepath = sys.argv[1]
with open(filepath, 'r') as f:
    content = f.read()

# old and new are passed via environment variables set by the caller
import os
old = os.environ['OLD']
new = os.environ['NEW']

if old not in content:
    print(f"ERROR: expected string not found in {filepath}", file=sys.stderr)
    print(f"  Looking for: {repr(old[:120])}", file=sys.stderr)
    sys.exit(1)

content = content.replace(old, new, 1)
with open(filepath, 'w') as f:
    f.write(content)
PYEOF
}

# =============================================================================
# CHANGE 1 — src/core/Config.h
#
# Add `float hudOpacity` to the Config::interface sub-struct, immediately
# after `hudScaleInteger`. This is the in-memory storage for the setting.
# =============================================================================

echo "[1/5] Config.h — adding float hudOpacity to interface struct"

export OLD='		float hudScale;
		bool hudScaleInteger;
		float bookScale;'

export NEW='		float hudScale;
		bool hudScaleInteger;
		float hudOpacity;
		float bookScale;'

replace "$SRC/core/Config.h"
echo "      OK"

# =============================================================================
# CHANGE 2 — src/core/Config.cpp  (four sub-changes)
#
# Config.cpp has three namespaces (Default, Key) and two functions (save,
# init) that all need to know about the new key.
# =============================================================================

echo "[2/5] Config.cpp — default value, key name, writer, reader"

# --- 2a: Default value ---
# The default MUST be 1.0f (fully opaque) so existing installs are unaffected.
# This value is used when hud_opacity is absent from cfg.ini (i.e. on first
# launch after the patch, before the user ever opens Options).

export OLD='	hudScale = 0.5f,
	bookScale = 1.f,'

export NEW='	hudScale = 0.5f,
	hudOpacity = 1.f,
	bookScale = 1.f,'

replace "$SRC/core/Config.cpp"

# --- 2b: Config key string ---
# This is the key name written to and read from cfg.ini.
# Snake_case, consistent with all other keys in this file.

export OLD='	hudScale = "hud_scale",
	hudScaleInteger = "hud_scale_integer",
	bookScale = "book_scale",'

export NEW='	hudScale = "hud_scale",
	hudScaleInteger = "hud_scale_integer",
	hudOpacity = "hud_opacity",
	bookScale = "book_scale",'

replace "$SRC/core/Config.cpp"

# --- 2c: Writer (Config::save) ---
# Without this, the setting is never saved to cfg.ini and resets on every launch.

export OLD='	writer.writeKey(Key::hudScale, interface.hudScale);
	writer.writeKey(Key::hudScaleInteger, interface.hudScaleInteger);
	writer.writeKey(Key::bookScale, interface.bookScale);'

export NEW='	writer.writeKey(Key::hudScale, interface.hudScale);
	writer.writeKey(Key::hudScaleInteger, interface.hudScaleInteger);
	writer.writeKey(Key::hudOpacity, interface.hudOpacity);
	writer.writeKey(Key::bookScale, interface.bookScale);'

replace "$SRC/core/Config.cpp"

# --- 2d: Reader (Config::init) ---
# Reads the key from cfg.ini (using the default if absent), then clamps it
# to [0, 1]. Clamping is essential — every float key in this file is clamped
# to prevent out-of-range values from a hand-edited cfg.ini.

export OLD='	interface.hudScaleInteger = reader.getKey(Section::Interface, Key::hudScaleInteger, Default::hudScaleInteger);
	float bookScale = reader.getKey(Section::Interface, Key::bookScale, Default::bookScale);'

export NEW='	interface.hudScaleInteger = reader.getKey(Section::Interface, Key::hudScaleInteger, Default::hudScaleInteger);
	float hudOpacity = reader.getKey(Section::Interface, Key::hudOpacity, Default::hudOpacity);
	interface.hudOpacity = glm::clamp(hudOpacity, 0.f, 1.f);
	float bookScale = reader.getKey(Section::Interface, Key::bookScale, Default::bookScale);'

replace "$SRC/core/Config.cpp"
echo "      OK"

# =============================================================================
# CHANGE 3 — src/gui/MainMenu.cpp  (two sub-changes)
#
# Adds the slider widget to InterfaceOptionsMenuPage and its callback.
# The slider sits directly below the HUD Scale slider, matching the brief.
# =============================================================================

echo "[3/5] MainMenu.cpp — HUD Opacity slider widget and callback"

# --- 3a: Slider widget ---
# Inserted between the hudScale slider block and the hudScaleInteger checkbox.
#
# Notes on implementation choices:
#   - getLocalised(..., "HUD Opacity"): two-arg form returns the fallback when
#     the key is absent. Since we don't modify .pak files, the key is always
#     absent and "HUD Opacity" is always shown.
#   - setValue(int(config.interface.hudOpacity * 10.f)): the SliderWidget
#     range is 0-10 integers; multiply by 10 to convert from the 0-1 float.
#   - boost::bind: same pattern as every other slider callback on this page.
#   - No recalcScale() call: opacity is read live from config on every frame,
#     unlike scale which requires recomputing cached pixel positions.

export OLD='			addCenter(sld);
		}

		{
			std::string label = getLocalised("system_menus_options_interface_hud_scale_integer");'

export NEW='			addCenter(sld);
		}

		{
			std::string label = getLocalised("system_menus_options_interface_hud_opacity", "HUD Opacity");
			SliderWidget * sld = new SliderWidget(sliderSize(), hFontMenu, label);
			sld->valueChanged = boost::bind(&InterfaceOptionsMenuPage::onChangedHudOpacity, this, arg::_1);
			sld->setValue(int(config.interface.hudOpacity * 10.f));
			addCenter(sld);
		}

		{
			std::string label = getLocalised("system_menus_options_interface_hud_scale_integer");'

replace "$SRC/gui/MainMenu.cpp"

# --- 3b: Callback ---
# state is 0-10; multiply by 0.1 to get 0.0-1.0.
# No recalc needed — render path reads config live every frame.

export OLD='	void onChangedHudScale(int state) {
		config.interface.hudScale = float(state) * 0.1f;
		g_hudRoot.recalcScale();
	}

	void onChangedHudScaleInteger(bool checked) {'

export NEW='	void onChangedHudScale(int state) {
		config.interface.hudScale = float(state) * 0.1f;
		g_hudRoot.recalcScale();
	}

	void onChangedHudOpacity(int state) {
		config.interface.hudOpacity = float(state) * 0.1f;
	}

	void onChangedHudScaleInteger(bool checked) {'

replace "$SRC/gui/MainMenu.cpp"
echo "      OK"

# =============================================================================
# CHANGE 4 — src/gui/Hud.cpp  (multiple sub-changes)
#
# This is the render path. Two concepts:
#
# A) hudAlpha() helper: scales vertex alpha by hud_opacity. Applied to every
#    EERIEDrawBitmap color argument inside HUD draw functions.
#
# B) OpModulate bracket: THE critical fix.
#
#    Arx's OpenGL texture stage defaults to GL_COMBINE_ALPHA = GL_REPLACE,
#    which means fragment alpha = texture alpha, ignoring vertex alpha entirely.
#    This is a known deviation from the GL default (see the TODO comment in
#    GLTextureStage.cpp). Without fixing this, hudAlpha() has zero effect.
#
#    The fix: wrap all HUD draws with setAlphaOp(OpModulate), which switches
#    the formula to: fragment_alpha = texture_alpha * vertex_alpha.
#    With vertex_alpha = hud_opacity * 255, this gives:
#      fragment_alpha = texture_alpha * hud_opacity
#    At hud_opacity=1.0: identical to vanilla. At 0.5: half opacity.
#
#    The bracket is restored to OpSelectArg1 at the end of HudRoot::draw()
#    so nothing outside the HUD is affected.
#
# =============================================================================

echo "[4/5] Hud.cpp — hudAlpha() helper, OpModulate bracket, draw-call changes"

# --- 4a: hudAlpha() helper ---
# Inserted after the indicatorHorizSpacing constant, before the first class.
# Static (file-local) — not needed outside Hud.cpp.
# Reads config directly; no caching needed (float field access is trivially cheap).

export OLD='static const int indicatorVertSpacing = 30;
static const int indicatorHorizSpacing = 20;'

export NEW='static const int indicatorVertSpacing = 30;
static const int indicatorHorizSpacing = 20;

// Scale vertex alpha by HUD opacity. Works for all blend modes once OpModulate is active.
static Color hudAlpha(Color c) {
	return Color(c.r, c.g, c.b, u8(float(c.a) * config.interface.hudOpacity));
}'

replace "$SRC/gui/Hud.cpp"

# --- 4b: HitStrengthGauge::draw ---
# The aim gauge. Both draws are inside an additive blend block; hudAlpha
# scales vertex alpha, which reduces the additive contribution.

export OLD='		EERIEDrawBitmap(m_rect, 0.0001f, m_fullTex, Color::gray(m_intensity));
	}

	EERIEDrawBitmap(m_rect, 0.0001f, m_emptyTex, Color::white);

	if(m_flashActive && player.m_skillFull.etheralLink >= 40) {

		float j = 1.0f - m_flashIntensity;
		Color col = (j < 0.5f) ? Color::rgb(j * 2.f, 1.f, 0.f) : Color::rgb(1.f, m_flashIntensity, 0.f);

		UseRenderState state(render2D().blendAdditive());
		EERIEDrawBitmap(m_hitRect, 0.0001f, m_hitTex, col);

	}'

export NEW='		EERIEDrawBitmap(m_rect, 0.0001f, m_fullTex, hudAlpha(Color::gray(m_intensity)));
	}

	EERIEDrawBitmap(m_rect, 0.0001f, m_emptyTex, hudAlpha(Color::white));

	if(m_flashActive && player.m_skillFull.etheralLink >= 40) {

		float j = 1.0f - m_flashIntensity;
		Color col = (j < 0.5f) ? Color::rgb(j * 2.f, 1.f, 0.f) : Color::rgb(1.f, m_flashIntensity, 0.f);

		UseRenderState state(render2D().blendAdditive());
		EERIEDrawBitmap(m_hitRect, 0.0001f, m_hitTex, hudAlpha(col));

	}'

replace "$SRC/gui/Hud.cpp"

# --- 4c: PurseIconGui — gold number ---

export OLD='		ARX_INTERFACE_DrawNumber(numberPos, player.gold, Color::white, m_scale);'
export NEW='		ARX_INTERFACE_DrawNumber(numberPos, player.gold, hudAlpha(Color::white), m_scale);'
replace "$SRC/gui/Hud.cpp"

# --- 4d: CurrentTorchIconGui::draw ---

export OLD='	EERIEDrawBitmap(m_rect, 0.001f, m_tex, Color::white);
}

ChangeLevelIconGui::ChangeLevelIconGui()'

export NEW='	EERIEDrawBitmap(m_rect, 0.001f, m_tex, hudAlpha(Color::white));
}

ChangeLevelIconGui::ChangeLevelIconGui()'

replace "$SRC/gui/Hud.cpp"

# --- 4e: ChangeLevelIconGui::draw ---
# Uses inherited standard blend; hudAlpha scales alpha.

export OLD='	EERIEDrawBitmap(m_rect, 0.0001f, m_tex, Color::gray(m_intensity));

	if(m_rect.contains(Vec2f(DANAEMouse))) {'

export NEW='	EERIEDrawBitmap(m_rect, 0.0001f, m_tex, hudAlpha(Color::gray(m_intensity)));

	if(m_rect.contains(Vec2f(DANAEMouse))) {'

replace "$SRC/gui/Hud.cpp"

# --- 4f: QuickSaveIconGui::draw ---
# This element uses BlendSrcColor,BlendOne (screen blend) — the blend factor
# is the RGB value, not alpha. Scale the gray value directly instead of alpha.

export OLD='	EERIEDrawBitmap(Rectf(Vec2f(0, 0), size.x, size.y), 0.f, tex, Color::gray(alpha));'
export NEW='	EERIEDrawBitmap(Rectf(Vec2f(0, 0), size.x, size.y), 0.f, tex, Color::gray(alpha * config.interface.hudOpacity));'
replace "$SRC/gui/Hud.cpp"

# --- 4g: MemorizedRunesHud::draw ---
# Rune symbols (standard blend) and the "missing rune" cross-out overlay.

export OLD='			EERIEDrawBitmap(rect, 0, tc, Color::white);

			if(!player.hasRune(player.SpellToMemorize.iSpellSymbols[i])) {
				UseRenderState state(render2D().blend(BlendInvDstColor, BlendOne).alphaCutout());
				EERIEDrawBitmap(rect, 0, cursorMovable, Color::gray(0.8f));'

export NEW='			EERIEDrawBitmap(rect, 0, tc, hudAlpha(Color::white));

			if(!player.hasRune(player.SpellToMemorize.iSpellSymbols[i])) {
				UseRenderState state(render2D().blend(BlendInvDstColor, BlendOne).alphaCutout());
				EERIEDrawBitmap(rect, 0, cursorMovable, Color::gray(0.8f * config.interface.hudOpacity));'

replace "$SRC/gui/Hud.cpp"

# --- 4h: HealthGauge::draw ---
# Two draws: the filled portion (colored, animated) and the empty shell (white).

export OLD='	EERIEDrawBitmap2DecalY(m_rect, 0.f, m_filledTex, m_color, (1.f - m_amount));
	EERIEDrawBitmap(m_rect, 0.001f, m_emptyTex, Color::white);
}


ManaGauge::ManaGauge()'

export NEW='	EERIEDrawBitmap2DecalY(m_rect, 0.f, m_filledTex, hudAlpha(m_color), (1.f - m_amount));
	EERIEDrawBitmap(m_rect, 0.001f, m_emptyTex, hudAlpha(Color::white));
}


ManaGauge::ManaGauge()'

replace "$SRC/gui/Hud.cpp"

# --- 4i: ManaGauge::draw ---

export OLD='	EERIEDrawBitmap2DecalY(m_rect, 0.f, m_filledTex, Color::white, (1.f - m_amount));
	EERIEDrawBitmap(m_rect, 0.001f, m_emptyTex, Color::white);'

export NEW='	EERIEDrawBitmap2DecalY(m_rect, 0.f, m_filledTex, hudAlpha(Color::white), (1.f - m_amount));
	EERIEDrawBitmap(m_rect, 0.001f, m_emptyTex, hudAlpha(Color::white));'

replace "$SRC/gui/Hud.cpp"

# --- 4j: MecanismIcon::draw (additive blend) ---

export OLD='	UseRenderState state(render2D().blendAdditive());

	EERIEDrawBitmap(m_rect, 0.01f, m_tex, m_color);
}


ScreenArrows::ScreenArrows()'

export NEW='	UseRenderState state(render2D().blendAdditive());

	EERIEDrawBitmap(m_rect, 0.01f, m_tex, hudAlpha(m_color));
}


ScreenArrows::ScreenArrows()'

replace "$SRC/gui/Hud.cpp"

# --- 4k: ScreenArrows::draw (additive blend) ---

export OLD='	Color lcolor = Color::gray(0.5f);

	EERIEDrawBitmap(m_left, 0.01f, m_arrowLeftTex, lcolor);'

export NEW='	Color lcolor = hudAlpha(Color::gray(0.5f));

	EERIEDrawBitmap(m_left, 0.01f, m_arrowLeftTex, lcolor);'

replace "$SRC/gui/Hud.cpp"

# --- 4l: PrecastSpellsGui::PrecastSpellIconSlot::draw (additive blend) ---

export OLD='	EERIEDrawBitmap(m_rect, 0.01f, m_tc, m_color);
}

PrecastSpellsGui::PrecastSpellsGui()'

export NEW='	EERIEDrawBitmap(m_rect, 0.01f, m_tc, hudAlpha(m_color));
}

PrecastSpellsGui::PrecastSpellsGui()'

replace "$SRC/gui/Hud.cpp"

# --- 4m: ActiveSpellsGui::ActiveSpellIconSlot::draw (additive blend) ---

export OLD='	EERIEDrawBitmap(m_rect, 0.01f, m_tc, m_color);

}'

export NEW='	EERIEDrawBitmap(m_rect, 0.01f, m_tc, hudAlpha(m_color));

}'

replace "$SRC/gui/Hud.cpp"

# --- 4n: DamagedEquipmentGui::draw (additive blend) ---

export OLD='		EERIEDrawBitmap(m_rect, 0.001f, iconequip[i], m_colors[i]);'
export NEW='		EERIEDrawBitmap(m_rect, 0.001f, iconequip[i], hudAlpha(m_colors[i]));'
replace "$SRC/gui/Hud.cpp"

# --- 4o: StealthGauge::draw (additive blend) ---

export OLD='	UseRenderState state(render2D().blendAdditive());

	EERIEDrawBitmap(m_rect, 0.01f, m_texture, m_color);
}'

export NEW='	UseRenderState state(render2D().blendAdditive());

	EERIEDrawBitmap(m_rect, 0.01f, m_texture, hudAlpha(m_color));
}'

replace "$SRC/gui/Hud.cpp"

# --- 4p: HudRoot::draw — enable OpModulate before all HUD draws ---
# See the large comment at the top of CHANGE 4 for why this is necessary.

export OLD='	UseRenderState state(render2D());
	UseTextureState textureState(getInterfaceTextureFilter(), TextureStage::WrapClamp);

	if(player.Interface & INTER_COMBATMODE) {'

export NEW='	UseRenderState state(render2D());
	UseTextureState textureState(getInterfaceTextureFilter(), TextureStage::WrapClamp);
	GRenderer->GetTextureStage(0)->setAlphaOp(TextureStage::OpModulate);

	if(player.Interface & INTER_COMBATMODE) {'

replace "$SRC/gui/Hud.cpp"

# --- 4q: HudRoot::draw — restore OpSelectArg1 after all HUD draws ---
# Must be at the very end of the function body so it always runs.

export OLD='	precastSpellsGui.draw();
	activeSpellsGui.update(hudSlider);
	activeSpellsGui.updateInput(mousePos);
	activeSpellsGui.draw();

}

void HudRoot::recalcScale()'

export NEW='	precastSpellsGui.draw();
	activeSpellsGui.update(hudSlider);
	activeSpellsGui.updateInput(mousePos);
	activeSpellsGui.draw();

	GRenderer->GetTextureStage(0)->setAlphaOp(TextureStage::OpSelectArg1);

}

void HudRoot::recalcScale()'

replace "$SRC/gui/Hud.cpp"

echo "      OK"

# =============================================================================
# CHANGE 5 — src/gui/hud/HudCommon.cpp
#
# HudIconBase::draw() is the base-class draw for the six side icons (backpack,
# book, purse, steal, level-up, change-level). It lives in a separate file.
#
# The hudAlpha() function from Hud.cpp is static (file-local) and not available
# here. The opacity expression is inlined directly instead of duplicating the
# helper — it is short enough that this is cleaner than adding a shared header.
#
# The OpModulate texture stage set in HudRoot::draw() is still active when
# HudIconBase::draw() is called, so vertex alpha takes effect here.
# =============================================================================

echo "[5/5] HudCommon.cpp — Config.h include and opacity in HudIconBase::draw()"

# --- 5a: Add Config.h include ---

export OLD='#include "game/Entity.h"
#include "graphics/Draw.h"'

export NEW='#include "game/Entity.h"
#include "core/Config.h"
#include "graphics/Draw.h"'

replace "$SRC/gui/hud/HudCommon.cpp"

# --- 5b: Apply opacity to both draws in HudIconBase::draw() ---
# First draw: standard blend (icon at rest)
# Second draw: additive blend (hover highlight — adds a brightened copy on top)

export OLD='	EERIEDrawBitmap(m_rect, 0.001f, m_tex, Color::white);

	if(m_isSelected) {
		UseRenderState state(render2D().blendAdditive());
		EERIEDrawBitmap(m_rect, 0.001f, m_tex, Color::white);
	}'

export NEW='	EERIEDrawBitmap(m_rect, 0.001f, m_tex, Color(255, 255, 255, u8(255.f * config.interface.hudOpacity)));

	if(m_isSelected) {
		UseRenderState state(render2D().blendAdditive());
		EERIEDrawBitmap(m_rect, 0.001f, m_tex, Color(255, 255, 255, u8(255.f * config.interface.hudOpacity)));
	}'

replace "$SRC/gui/hud/HudCommon.cpp"

echo "      OK"

# =============================================================================
# Done
# =============================================================================

echo ""
echo "=== Patch applied successfully ==="
echo "Next steps:"
echo "  cd /path/to/build"
echo "  ninja arx          (or cmake --build .)"
